# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  resources:
    # Apps
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Google.Chrome
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.PowerToys
        source: winget

    # CLIs
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Amazon.AWSCLI
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: GitHub.cli
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: ezwinports.make
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Hashicorp.Terraform
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: JesseDuffield.Lazydocker
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: FiloSottile.mkcert
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Neovim.Neovim
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: tree-sitter.tree-sitter-cli
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: sharkdp.fd
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: junegunn.fzf
        source: winget

    # SDKs
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Microsoft.DotNet.SDK.10
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: GoLang.Go
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: OpenJS.NodeJS
        version: 24.10.0
        source: winget

    # AI tools
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: SST.opencode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: GitHub.Copilot
        source: winget

    # Windows UI
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: AmN.yasb
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: glzr-io.glazewm
        source: winget
